### ISSUE TITLE
Not working with custom stream

### ISSUE THREAD

**Issue by mcollina** [matthewmueller/sutra#11]
Currently it is impossible to pass a Wrtiable as part of the `pipe` command:

``` js
var loolog = require('loo')('test')
var dest = require('fs').createWriteStream('myfile')
loolog.pipe(dest)
```

Results in

```
Error: Cannot pipe, not readable
    at WriteStream.Writable.pipe (_stream_writable.js:161:22)
    at Function.pipe (/Users/matteo/Repositories/pino/node_modules/loo/index.js:144:14)
```

It is highly related to: https://github.com/matthewmueller/loo/blob/master/index.js#L141-L144

**Comment by matthewmueller** [comment]
ah yep, just an oversight that i need to finish up. was focusing on the API first. would love to see how loo compares to pino though. nice work on that library :-D

**Comment by mcollina** [comment]
Ping me when this is fixed, I'll get that added to the benchmarks! :)
